### ISSUE TITLE
`sig.symbols` currently ignored in calls to `aov_car()`

### ISSUE THREAD

**Issue by crsh** [singmann/afex#17]
Currently, when calling `aov_car()` passing `sig.symbols` to in the `anova_table` list has no effect. This is because `print.afex_aov()` passes the `anova_table` object to `nice()` and `sig.symbols` is lost. A straight forward solution for this would be to add another attribute to either the entire `afex_aov` object or to `anova_table` (I would probably prefer the latter). `nice()` could then use the attribute value if nothing is explicitly passed when calling the function. I think it would also be handy to add `sig.symbols` to `afex_options()` so they could be set once globally for all analyses. Any thoughts on this?

One other thing I was wondering about: `print.afex_aov()` currently does not print the `sig.symbol`-legend (e.g., `Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1`) but the legend _is_ printed by `print.anova()`, which is used for the `anova_table` object. Do you think this is something to standardize while working on this?

**Comment by singmann** [comment]
I agree with all ideas in the first paragraph. Both, adding the attribute to `anova_table` and adding it to `afex_options` is very reasonable. Before you start implementing this, consider however the following two things:
- I plan to change all argument names to use `_` instead of `.` and deprecate the old spelling (e.g., `sig.symbols` to `sig_symbols`). Should I do this perhaps before adding another attribute? I plan to do this still this month.
- I am somewhat unhappy with the design of `afex_options()` as it does not work as other options in R. For example, you cannot do the following which usually works with R.
```
opt_sav <- afex_options()  # safe options
afex_options(type = 2) # change some options
... # do something
afex_options(opt_sav)  # reset options
```
I really would like to harmonize this so that it works as usual R options, but I am not sure it is possible with the possible implementation. I am not sure if it makes sense to implement new things now or to wait (probably no problem to implement this now).

And I also think it would be a nice idea to add the legend to the `print.afex_aov` method. Probably a good idea to add it to the `print.mixed` method as well as add the `sig_symbols` argument to `mixed()`.

**Comment by crsh** [comment]
We could agree that I take care of changing `sig.symbols` to `sig_symbols` while working on this and you do all other changes. I can also wait before starting on this to avoid wrestling merge conflicts, though. I'll leave this up to you.

With regards to `afex_options()`, again, I'm happy to wait, but naively I don't think adding another element would make the planned changes more complicated. I would probably still wait for `sig_symbols` before starting on this, though.

`print.mixed()` was next on my agenda of things to look at. I think its worth looking more closely at consistent behavior of `aov_car()` and `mixed()` following the recent changes to `aov_car()` and the related methods. If this is fine by you, I'll finish the issues mentioned herein for `aov_car()` in one pull request and then tackle `mixed()` in the one after that.

**Comment by singmann** [comment]
I have made the changes to `sig_symbols`. It now gives a warning if the old version is used, but it still works. See below. So you can start working on this part.

And I agree with everything else you suggest. `afex_options()` can be dealt with later independent if we add something now or not.. And tackling `mixed()` after `sig_symbol` is implemented sound slike a good plan.

```
data(md_12.1)
aov_ez("id", "rt", md_12.1, within = c("angle", "noise"), anova_table = list(sig.symbols = c(" ", " a", " aa", " aaa")), return = "nice")
## Anova Table (Type 3 tests)
## 
## Response: rt
##        Effect    df     MSE         F ges p.value
## 1       angle 2, 18 3560.00 40.72 aaa .39  <.0001
## 2       noise  1, 9 8460.00 33.77 aaa .39   .0003
## 3 angle:noise 2, 18 1160.00 45.31 aaa .19  <.0001
## Warning message:
## 'sig.symbols' is deprecated; use 'sig_symbols' instead 
```

**Comment by singmann** [comment]
I think we can close this now. Or do you think there is more to this issue?

**Comment by crsh** [comment]
I think we are done here.
