### ISSUE TITLE
Afex or car ANOVA models vs lme4?. Observed variables

### ISSUE THREAD

**Issue by skanskan** [singmann/afex#19]
Hello.

I don't know if this is the proper place to ask this 
just in case, I've also posted my question here

> https://stackoverflow.com/questions/37102075/how-to-convert-afex-or-car-anova-models-to-lmer-observed-variables

but nobody replies.

In the afex package we can find this example of ANOVA analysis:
data(obk.long, package = "afex")
# estimate mixed ANOVA on the full design:
# can be written in any of these ways: 

```
aov_car(value ~ treatment * gender + Error(id/(phase*hour)), data = obk.long,
        observed = "gender")

aov_4(value ~ treatment * gender + (phase*hour|id), data = obk.long,
        observed = "gender")

aov_ez("id", "value", obk.long, between = c("treatment", "gender"), 
       within = c("phase", "hour"), observed = "gender")
```

My question is, How can I write the same model in lme4? In particular, I don't know how to include the "observed" term?

If I just write
```
lmer(value ~ treatment * gender + (phase*hour|id), data = obk.long,
     observed = "gender")
```
I get an error telling that observed is not a valid option.

Furthermore, if I just remove the observed option lmer produces the error:
`Error: number of observations (=240) <= number of random effects (=240) for term (phase * hour | id); the random-effects parameters and the residual variance (or scale parameter) are probably unidentifiable.`

Where in the lmer syntax do I specify the "between" or "within" variable?. As far as I know you just write the dependent variable on the left side and all other variables on the right side, and the error term as (1|id).

The package "car" uses the idata for the intra-subject variable.

**Comment by singmann** [comment]
As the help page for `aov_car` clarifies,  `observed` is only relevant for the correct calculation of generalized eta-squared, which is an effect size measure. It does not affect the calculation of the ANOVA otherwise. 

> character vector indicating which of the variables are observed (i.e, measured) as compared to experimentally manipulated. The default effect size reported (generalized eta-squared) requires correct specification of the observed (in contrast to manipulated) variables.

As `mixed` does not offer generalized eta-square or any other standardized effect size measure, `observed` does not work in `mixed`. 

Unfortunately, I would not recommend to do what you want to do. Using a mixed model for a data set without replications within each cell of the design per participant is somewhat questionable as it is not really clear how to specify the random effects structure. Importantly, the Barr et al. maxim of "keep it maximal" does not work here as you realized. The problem is that the model is overparametrized. Consequently, I recommend using the ANOVA. More discussion on exactly this question can be found on [crossvalidated](http://stats.stackexchange.com/a/131011/442).

**Comment by skanskan** [comment]
Thank you
