### ISSUE TITLE
Intercept-less models broken

### ISSUE THREAD

**Issue by LostLinguist** [singmann/afex#26]
The `mixed()` function fails to handle models with a suppressed intercept. Intercept-less models are useful as a way of tricking lme4 into doing multivariate analysis. (The convential trick of using `cbind(incidence,size) ~ period + (1|herd)` doesn't work.)
```
> library(afex)
> library(reshape2)
> d = melt(cbpp,id.vars=c('period','herd'))
> m = mixed(value ~ 0 + variable:period + (0+variable|herd),d)
Contrasts set to contr.sum for the following variables: variable, period, herd
Fitting 2 (g)lmer() models:
[.Error in x[, ii] : subscript out of bounds
```

**Comment by singmann** [comment]
The problem is that the model you want to fit has only one term, the `variable:period` interaction. There is no way `mixed` can test this interaction. Remember that mixed removes all the term in a stepwise manner and tests them against the remaining model. If the interaction is removed, the model has no more fixed effect so cannot be fitted. That is why one also cannot test a model with `mixed` that only has an intercept and not other terms (there remains no model to compare it with after removing the single term).

However, you can test a binomial model, by transforming the frequencies to a probability:

```
cbpp$prob <- with(cbpp, incidence / size)
m1p <- mixed(prob ~ period + (1 | herd), weights = size, family = binomial, data = cbpp, method = "LRT")
m1p
##   Effect df     Chisq p.value
## 1 period  3 25.61 ***  <.0001
```

**Comment by LostLinguist** [comment]
OK, I agree that that was a particularly bad example of an intercept-less model. How about the below, though? (the model doesn't make any sense but just to use it as an example problem)

```
> mixed(Petal.Width ~ 0 + Sepal.Length + Sepal.Width + Petal.Length + (1|Species),iris)
Contrasts set to contr.sum for the following variables: Species
Numerical variables NOT centered on 0 (i.e., interpretation of all main effects might be difficult if in interactions): Sepal.Length, Sepal.Width, Petal.Length
Fitting 4 (g)lmer() models:
[.Error in x[, ii] : subscript out of bounds
```

Again, with the intercept, this model is fit just fine.

**Comment by singmann** [comment]
Can you tell me what your goal is? I have the suspicion that the tests of the intercept less models are problematic and are not worth to implement.
You can fit binomial models with `cbind(incidence,size) ~ period + (1|herd)` by transforming the left side to a proportion and passing the number of observations via `weights`.

**Comment by cvoeten** [comment]
Of course. I have a lot of trials of EEG data (32 electrodes, 900-ms timeslices). I'm trying to determine which electrodes & at what timepoints I should be looking at to run my statistical analyses. This is normally done by running, at every timepoint, a multivariate ANOVA with 32 dependent variables, and plotting the resulting 32 * 900 (assuming for simplicity a sampling rate of 1ms) p-values in a heatmap (with 32 electrodes on the y axis, time on the x axis, p-value as the color). This helps you determine your time window and electrode subset on which you want to run your actual statistical analysis. Note that this method of running 32 * 900 F-tests has a huge multiple comparisons problem, which is dealt with by running a permutation equivalent of the ANOVA analysis.

What I want to do is see whether the results I obtain from this standard methodology will be different if I use mixed-effects models instead of ANOVAs (which cannot incorporate random effects). There is no permutation test for lmer models as far as I know, but a similar approach is available in parametric bootstrapping. This is what led me to `afex::mixed`. (I realize that using bootstrapping with my current approach will be prohibitively slow, but I can cluster some of the electrodes/bin my timepoints/etc.)

The problem then is that I want to somehow run a multivariate model (it's actually linear regression, the - poor - example above was simply the first freely-available multivariate dataset I could find, which happened to be binomial instead of gaussian only by coincidence). The `cbind(electrode1,electrode2,...` trick doesn't work with `mixed`, but neither does the workaround described in comment 1, viz. to melt my 32 dependent variables into a factor and using that as the first predictor in the model - even before the intercept. The latter seemed a more general problem than the former, hence why I reported that as a bug.

**Comment by LostLinguist** [comment]
(sorry, accidentally posted this with another account, reposting:)

Of course. I have a lot of trials of EEG data (32 electrodes, 900-ms timeslices). I'm trying to determine which electrodes & at what timepoints I should be looking at to run my statistical analyses. This is normally done by running, at every timepoint, a multivariate ANOVA with 32 dependent variables, and plotting the resulting 32 * 900 (assuming for simplicity a sampling rate of 1ms) p-values in a heatmap (with 32 electrodes on the y axis, time on the x axis, p-value as the color). This helps you determine your time window and electrode subset on which you want to run your actual statistical analysis. Note that this method of running 32 * 900 F-tests has a huge multiple comparisons problem, which is dealt with by running a permutation equivalent of the ANOVA analysis.

What I want to do is see whether the results I obtain from this standard methodology will be different if I use mixed-effects models instead of ANOVAs (which cannot incorporate random effects). There is no permutation test for lmer models as far as I know, but a similar approach is available in parametric bootstrapping. This is what led me to afex::mixed. (I realize that using bootstrapping with my current approach will be prohibitively slow, but I can cluster some of the electrodes/bin my timepoints/etc.)

The problem then is that I want to somehow run a multivariate model (it's actually linear regression, the - poor - example above was simply the first freely-available multivariate dataset I could find, which happened to be binomial instead of gaussian only by coincidence). The cbind(electrode1,electrode2,... trick doesn't work with mixed, but neither does the workaround described in comment 1, viz. to melt my 32 dependent variables into a factor and using that as the first predictor in the model - even before the intercept. The latter seemed a more general problem than the former, hence why I reported that as a bug.
