### ISSUE TITLE
allFit does not work with (0+var|group) and expand_re=TRUE

### ISSUE THREAD

**Issue by pvavra** [singmann/afex#32]
I'm using the `expand_re=TRUE` option for automatically converting my factors into vectors in the random effects structure which works fine. 

However, passing the full model to `allFit` does not work if the intercept has been removed from the random effects structure, using the `(0 + x | group)` syntax. Instead, each optimizer returns an error message that the automatically generated vector hasn't been found. Keeping the intercept in does work just fine.

a minimal reproducible example (using example from `afex::allFit`):
```
library(afex)
data("sk2011.2")
sk2_aff <- droplevels(sk2011.2[sk2011.2$what == "affirmation",])

# the following works - taken from example section
sk_m2 <- mixed(response ~ instruction*inference*type+(inference*type||id), sk2_aff,
               expand_re = TRUE)
allFit(sk_m2$full.model)

# but this one doesn't pass the expanded vectors to allFit:
sk_m3 <- mixed(response ~ instruction * inference * type + (0 + inference | id), sk2_aff,
               expand_re = TRUE) # runs just fine
allFit(sk_m3$full.model) # runs, but returns same error for all optimizers: <simpleError in eval(expr, envir, enclos): object 're1.inferenceMP' not found>
```

**Comment by singmann** [comment]
If you use the latest version of `afex` (in which `allFit` is `all_fit` and `full.model` is `full.model`) you can get this to work by passing the data slot as well:

```
library(afex)
data("sk2011.2")
sk2_aff <- droplevels(sk2011.2[sk2011.2$what == "affirmation",])
sk_m3 <- mixed(response ~ instruction * inference * type + (0 + inference | id), sk2_aff,
               expand_re = TRUE) 
all_fit(sk_m3$full_model, data=sk_m3$data)
```

In addition, `mixed` now supports `all_fit` directly as an argument. If `TRUE` it automatically tries all optimizer and retains only the result that provided the best fit.

```
sk_m3b <- mixed(response ~ instruction * inference * type + (0 + inference | id), sk2_aff,
                expand_re = TRUE, all_fit = TRUE) 

attr(sk_m3b, "all_fit_selected")
attr(sk_m3b, "all_fit_logLik")
```

The additional code just shows you the fit of the different optimizers. Note that to use all available optimizers, you need to load two more packages:

```
require(optimx)
require(dfoptim)
```

PS: It is really weird that the first example worked in your case. It should not because of the same reason why the second one fails and does also not work for me with the latest version.
