### ISSUE TITLE
don't overwrite global (g)lmer() function

### ISSUE THREAD

**Issue by ashenkin** [singmann/afex#33]
Hi there,

Recent behavior in afex seems to have changed.  I need my lmer models to be class lme4:lmer (stargazer, for example, chokes on lmerTest::lmer objects).  However, when i set afex_options(lmer_function = "lme4"), mixed() fails.  Rewriting my code to use lme4::lmer instead of just lmer is pretty ugly.  Would it be possible to allow options to be separately set for the global lmer function and the lmer afex uses internally separately?  If there's a better solution, I'm all ears...

Thanks for the nice package, by the way.

Allie

**Comment by singmann** [comment]
That looks like a sensible request and bug report all in once. I will try to get back to you with a solution over the weekend as I will be at a workshop beginning of next week. Please remind me should you not hear from me within the next week.

**Comment by singmann** [comment]
Unfortunately, there is no easy way to change that `afex` reexports `lmerTest::lmer` per default. At least I am not aware of a way to alter what happens when a package is attached.

However, a simple way to circumvent the issue is to simply bind `lme4::lmer` to `lmer` in the global environment:

```
require(afex)

fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)

stargazer::stargazer(fm1)
# Error in objects[[i]]$zelig.call : 
#   $ operator not defined for this S4 class

lmer <- lme4::lmer
fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
stargazer::stargazer(fm1) # works
```

However, the fact that `afex_options(lmer_function = "lme4")` leads `mixed` to fail is not nice, but also unavoidable for methods `'KR'` and `'S'`. I think this might perhaps need a better error message.

```
afex_options(lmer_function = "lme4")
data(md_15.1)

t15.4a <- mixed(iq ~ timecat + (1+time|id),data=md_15.1) #default method 'KR' and 'S' fail
t15.4a <- mixed(iq ~ timecat + (1+time|id),data=md_15.1, method = "nested-KR") # still works
```

Please let me know if this solves the problem for you.

**Comment by ashenkin** [comment]
Thanks @singmann.  I had considered overwriting lmer as you suggest, but it then breaks `mixed`, which is expecting `lmer` to point to `lmerTest:lmer`.

```
> library(afex)
> fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
> lmer <- lme4::lmer
> mixed(fm1)
Formula (the first argument) converted to formula.
Error in model.matrix.default(rh2, data = data) : 
  argument "data" is missing, with no default
```

The overwriting solution can be done in a number of ways (e.g. refactor all code to specify `lmer4::lmer`, wrap each call to `mixed` with two calls to `afex_options`, etc...).  I'm wondering though: what about refactoring all calls within `afex` to specify `lmerTest::lmer`?  Or rather, make the call within afex dynamic based on `afex_options(lmer_function)`...  So, maybe one way to do it would be to, for example, define `afexlmer <- lmerTest::lmer` or `afexlmer <- lme4::lmer` depending on the option...  That basically shifts the burden to you (not my intention), but I think it also kind of accomplishes what a package more or less is supposed to do: perform stuff with as little effect on the global namespace as possible.

Taking a quick look at the code, this is what you seem to do already in `mixed`:
```
if (afex_options("lmer_function") == "lmerTest") mf[[1]] <- quote(lmerTest::lmer)
else if (afex_options("lmer_function") == "lme4") mf[[1]] <- quote(lme4::lmer)
```

So I'm not exactly sure where the global call to lmer is getting overwritten, and I'm not sure of the need for that overwrite; perhaps it's happening in the order of package loading?

**Comment by singmann** [comment]
Your example does not work, because `data` is missing. If you correctly pass the `data` argument, everything works fine.

```
library(afex)
fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
lmer <- lme4::lmer
mixed(fm1, sleepstudy)
# Mixed Model Anova Table (Type 3 tests, KR-method)
# 
# Model: Reaction ~ Days + (Days | Subject)
# Data: sleepstudy
#   Effect    df         F p.value
# 1   Days 1, 17 45.85 ***  <.0001
# ---
#   Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘+’ 0.1 ‘ ’ 1
```
Please note that I do not suggest to use `mixed` in this way. I highly suggest to use:
`mixed(Reaction ~ Days + (Days | Subject), sleepstudy)`

And as you correctly assume, all calls within `mixed` use the value of `afex_options(lmer_function)`. `lmer` is never called outside of this. And even if, this would not be affected.

More precisely, due to the `NAMESPACE` mechanism a function in the global environment (`.GlobalEnv`) to which you assign with `lmer <- lme4::lmer` cannot really override what is called inside a function in a package. Functions in packages are either a directly imported from a package or are called using `package::function`. This is true at least for all packages on `CRAN`. This means whatever happens in the global environment has generally no effect for code inside packages.
