### ISSUE TITLE
Avoid data.table dependency?

### ISSUE THREAD

**Issue by steveharoz** [singmann/afex#53]
There is a major bug with the data.table, preventing it from loading in R 3.5+ on Windows. See more [here](https://stackoverflow.com/questions/49838553/data-table-package-in-r-3-5-does-not-install).

Unfortunately, afex will not load without the data.table library. So Afex is dead on Windows for now.

```
> library(afex)
Error: package or namespace load failed for ‘afex’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘data.table’
```

Is there any possibility of removing the data.table dependency from afex?

**Comment by singmann** [comment]
I am sorry for my late reply, but I was travelling quite a bit in the last two weeks and could not check it. Mainly because `data.table` is not a direct dependency of `afex` (actually, I am not sure which package that `afex` requires depends on `data.table`). However, it seems that `data.table` builds now on CRAN without any problem (version 1.11.2): https://cran.r-project.org/web/checks/check_results_data.table.html

Is this problem still persistent and the issue still current?

**Comment by steveharoz** [comment]
Just tried again. Works now. Thank you.
