### ISSUE TITLE
return = "merMod" doesn't return merMod object

### ISSUE THREAD

**Issue by maarten-jung** [singmann/afex#54]
`mixed(..., return = "merMod")`, and thus `lmer_alt()`, call `lmerTest::lmer()` by default and therefore return an object of class `lmerModLmerTest`.  
According to the documentation 
> lmer_alt is simply a wrapper for mixed that only returns the "merMod" object and correctly uses the || notation to remove correlation among factors, but otherwise behaves like g/lmer

IMHO it would be more appropriate to fit the model via `lme4::lmer()` in this case. This would also save a lot of computation time as for the new lmerTest version the Hessian and derivatives needed for evaluation of degrees of freedom are computed directly within `lmerTest::lmer()`. And AFAICS these are only needed for calls to `mixed()` where `return != "merMod"`. Besides that, `merMod` objects can be converted to `lmerModLmerTest` objects via `lmerTest::as_lmerModLmerTest(object)`.

@singmann if this makes sense to you an easy fix would be to add `mf[[1]] <- quote(lme4::lmer)` after line 308 in `mixed.R`

**Comment by singmann** [comment]
The choice of function can already be changed via `afex_options(lmer_function)`. See:

```
library("afex")
data("Machines", package = "MEMSS") 

m1 <- lmer_alt(score ~ Machine + (Machine|Worker), data=Machines)
class(m1)
# [1] "lmerModLmerTest"
# attr(,"package")
# [1] "lmerTest"

afex_options(lmer_function = "lme4")
m2 <- lmer_alt(score ~ Machine + (Machine|Worker), data=Machines)
class(m2)
# [1] "lmerMod"
# attr(,"package")
# [1] "lme4"
```
But I agree that this is not reflected in the current documentation. I will update this and leave the issue open until it is updated.

Thanks for the report.

**Comment by maarten-jung** [comment]
I'm aware of this. But are there any advantages of returning a `lmerModLmerTest` object in this case? If one uses `lmer_alt()` as a replacement for `lmer()` that removes correlation among factors for, say, model reduction there would be no need to calculate submodels and p-values until the very end where one can use `mixed()` to do this.

**Comment by singmann** [comment]
I have updated the documentation to better reflect this behavior.

To answer your question: It indeed seems a little counter intuitive that `lmer_alt` does not return a `merMod` object by default. However, this is a consequence of how `mixed` works internally and changing it such that `lmer_alt` per default uses a different function seems a little overkill. 

If the code would not be too complicated, I would however be willing to consider a pull request. I am closing this issue for now, but will reopen in case you decide to want a further discussion.

**Comment by maarten-jung** [comment]
Thanks for addressing this. 
Not sure if I'm missing something here but wouldn't adding `mf[[1]] <- quote(lme4::lmer)` after line 308 in `mixed.R` (as I suggested in my first post) fix it?  AFAICS this results in using `lme4::lmer` every time 
`return == "merMod"` is requested which seems to be an intuitive default behaviour.

**Comment by singmann** [comment]
I agree that it is slightly counter intuitive to return an object of class `"lmerModLmerTest"` instead of class `"merMod"` if `return == "merMod"`, but one of the design goals of `afex` is to provide reasonable defaults that users are generally happy with. And I believe that the output from `lmerTest::lmer`, by having *p*-values, is more convenient in most cases. Consequently, I feel that this is the better default, despite it somewhat contradicting the argument.

The problem with your suggestion is that it would prevent the user to obtain an object of class `"lmerModLmerTest"`. Now objects of both classes are possible and the actual return value is determined via `afex_options`. 

I have updated the documentation once more which should makes it quite clear what is happening and how to obtain either object. Let me know if you feel there is something to add to the documentation, but I am not willing to disable the possibility for obtaining an object returned by `lmerTest`. It just seems more convenient in most cases with little additional costs.

**Comment by maarten-jung** [comment]
> [...] one of the design goals of afex is to provide reasonable defaults that users are generally happy with. [...] Consequently, I feel that this is the better default, despite it somewhat contradicting the argument.

This makes sense to me and indeed I agree - getting *p* values is probably exactly the reason why many users choose `afex`. 

> I have updated the documentation once more which should makes it quite clear what is happening and how to obtain either object.

Thank you. I think it sufficiently describes the points discussed here and/or how the user can get what he/she wants.
